/**
 * ASCII map import/export — the labyrinth-larry idiom ("ASCII map patches with a
 * legend") so levels can be written by hand, pasted into issues, diffed in git
 * and generated by other tools. Each entity's `glyph` is its character;
 * '.' and ' ' are empty floor.
 */
import type { GameSpec, Level } from './schema.ts'

export function levelToAscii(spec: GameSpec, level: Level): string {
  const glyph = new Map(spec.entities.map((e) => [e.id, e.glyph]))
  const rows: string[] = []
  for (let y = 0; y < level.height; y++) {
    let row = ''
    for (let x = 0; x < level.width; x++) row += glyph.get(level.cells[y * level.width + x]) ?? '.'
    rows.push(row)
  }
  return rows.join('\n')
}

export function legend(spec: GameSpec): string {
  return ['. = floor', ...spec.entities.map((e) => `${e.glyph} = ${e.name} (${e.kind})`)].join('\n')
}

/**
 * Parse rows of glyphs into a cells array. The level is sized to the text
 * (longest row × row count). Unknown glyphs are reported, not thrown, so a
 * paste with one typo still loads.
 */
export function asciiToCells(spec: GameSpec, text: string): { width: number; height: number; cells: string[]; unknown: string[] } {
  const byGlyph = new Map(spec.entities.map((e) => [e.glyph, e.id]))
  const rows = text.replace(/\r/g, '').split('\n').filter((r, i, all) => r.length || i < all.length - 1)
  while (rows.length && !rows[rows.length - 1].trim()) rows.pop()
  const height = Math.max(1, rows.length)
  const width = Math.max(1, ...rows.map((r) => r.length))
  const cells = new Array(width * height).fill('')
  const unknown = new Set<string>()
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x]
      if (ch === '.' || ch === ' ') continue
      const id = byGlyph.get(ch)
      if (id) cells[y * width + x] = id
      else unknown.add(ch)
    }
  })
  return { width, height, cells, unknown: [...unknown] }
}
